name: Build QEMU for Raspberry Pi 4 Emulation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: |
        docker build -t qemu-arm-emulation .

    - name: Run Docker Container
      run: |
        docker run --rm qemu-arm-emulation \
          -M raspi4 \
          -kernel /qemu/firmware/kernel7l.img \
          -drive file=/qemu/firmware/rootfs.img,format=raw,if=virtio \
          -m 2G \
          -serial stdio \
          -append "root=/dev/vda2 console=ttyAMA0" \
          -net nic -net user

